### ISSUE TITLE
Move from async_std::task to futures::executors::threadpool

### ISSUE THREAD

**Issue by qdot** [buttplugio/buttplug-rs#112]
Using the async_std task system locks us into async_std as a runtime, which is not something we want in a library. We should push runtime decisions down to the things that need them as features, which will mostly be things with network requirements (connectors, forwarders). For everything else, futures::executors::threadpool should be fine. (Idea taken from https://bionic.fullstory.com/rust-at-fullstory-part-2/, thanks @luser)

**Comment by luser** [comment]
You might additionally consider designing things so that you expose an API that accepts something that implements [`futures::task::Spawn`](https://docs.rs/futures/0.3.4/futures/task/trait.Spawn.html) (or maybe [`SpawnExt`](https://docs.rs/futures/0.3.4/futures/task/trait.SpawnExt.html) if you need that). That'd let callers provide their own `ThreadPool` or other such executor for maximum flexibility. You can see a good design pattern for this in `std::collections::HashMap`, where it has a third type parameter for the hasher that has a sensible default (`HashMap<K, V, S = RandomState>`). `HashMap::new` uses the default, but [`HashMap::with_hasher`](https://doc.rust-lang.org/std/collections/struct.HashMap.html#method.with_hasher) lets callers provide their own.

Having multiple `impl` blocks with different sets of type parameters is a really neat trick in Rust! I did something similar in my `minidump` crate, providing a [`Minidump::read_path`](https://github.com/luser/rust-minidump/blob/aaa0e8cff6d4ec63cbdccd2a1b4df796dec35b24/src/minidump.rs#L1412) constructor that always uses `Mmap` to access the file, but internally calls the more-generic [`Minidump::read`](https://github.com/luser/rust-minidump/blob/aaa0e8cff6d4ec63cbdccd2a1b4df796dec35b24/src/minidump.rs#L1433) which works for anything that's `Deref<Target=[u8]>`.

**Comment by qdot** [comment]
@luser TIL neither Tokio or async_std has support for futures::task::Spawn/SpawnExt out of the box. I guess they're not THAT bad to write my own wrapper for. My own fault for running headlong into a very new ecosystem. :)

**Comment by qdot** [comment]
Created my own smaller version of async-executors (), mainly because of async_std version mismatch but it works well enough. Shipping in 0.4.
