### ISSUE TITLE
Websocket connection to rust connects but no reply is sent to the client including the devices connected.

### ISSUE THREAD

**Issue by Fedack** [buttplugio/buttplug-rs#115]
Websockets connection to the Rust server doesn't send the expected success package including the device list which leads to the the hanging of any await function on the client side. Client DOES connect, but isn't aware and just hangs.

**Expected behavior**
Connection to the server should send back the device connected.

**Actual behavior**
When connecting to the server, there is no answer from the answer that allows the continuation of the await procedure. That means that the client basically hang at that point.

**Additional context**
This was tested using both C# and Python client.

**Comment by qdot** [comment]
99% sure this is #114. Try the v3 release, just happened like 2 hours ago. I'll test on my end too.

**Comment by qdot** [comment]
Yup, verified on my end, this is fixed by #114, which landed in Buttplug-rs 0.2.4 and is in intiface-cli-rs v3.

Note that RequestDeviceList will still return a null list, which is another bug, possibly up in the CLI, but it does at least returns something so I'm good to call this fixed. I'll link followup here once I figure out where it should be, working on that now.

**Comment by Fedack** [comment]
Great. Thanks for the rapid fix :)
