### ISSUE TITLE
Prettylove Archenemy reported working on WASM but not Rust

### ISSUE THREAD

**Issue by qdot** [buttplugio/buttplug-rs#295]
Prettylove Archenemy reported worked in WASM, but doesn't connect in Intiface CLI rs.

**Comment by blackspherefollower** [comment]
Closed #301 in favour of the pre-existing issue.

Additional detail:

Describe the bug
About half of my PrettyLove devices appear in the device list, but do nothing when sent VibrateCmd.
All PrettyLove devices use the exact same code, UUIDs, etc.
This is limited to Win10 btleplug (WebBluetooth and "Bluetooth LE Explorer" both work fine). I haven't tested on Linux or Mac.
One of the problematic devices is the Archenermy (oscillating prostate massager).

I'm logging this here, since it's device specific, but if I can narrow the bug down to a specific area of code, I may report this on btleplug too.

Expected behaviour
The device vibrates/oscillates when sent a suitable command.

Actual behaviour
The devices does not respond.


@Tigrejor Reports nether WebBluetooth or CLI are working on Linux.

Testing WebBluetooth on Android is successful

**Comment by blackspherefollower** [comment]
The deprecated buttplug-c# also fails to control the Archenemy

**Comment by qdot** [comment]
Desktop WASM/WebBluetooth worked on Windows Chrome, not sure why Linux didn't.

I believe WASM is currently sending everything as WriteWithResponse, which wasn't obvious from the codebase. Changing the desktop impl to do this (just flipping the boolean in the DeviceWriteCmd struct) seems to have fixed this on desktop. Will land as part of v3.

**Comment by qdot** [comment]
Confirmed working with initial reporter, will close with v3 release.
